baseURL: "https://sfraney.github.io/ReturnToHer/"
languageCode: "en-us"
title: "Return To Her"
theme: "hugo-profile"

# Minimal params for hugo-profile theme (can be expanded later)
params:
  title: "Return To Her"
  description: "A personal blog and portfolio."
  # Add more params as needed
