baseURL: "https://sfraney.github.io/ReturnToHer/"
languageCode: "en-us"
title: "Return To Her"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

#services:
  #googleAnalytics:
    #id: G-MEASUREMENT_ID
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /posts
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about
      weight: 2

params:
  title: "Return To Her"
  description: "A personal blog about returning to what matters most."
  favicon: "/fav.png"
  useBootstrapCDN: false
  mathjax: false
  animate: true
  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark
  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
  navbar:
    align: ms-auto
    brandName: "Return To Her"
    disableSearch: false
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Your Name"
    subtitle: "I write about what matters"
    content: "Welcome to my journey of rediscovering joy, peace, and fulfillment."
    image: /images/hero.svg
    bottomImage:
      enable: true
    button:
      enable: true
      name: "Read the Blog"
      url: "/posts"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/sfraney
        - icon: fab fa-x-twitter
          url: https://twitter.com
      customIcons:
        - icon: /fav.png
          url: "https://sfraney.github.io/ReturnToHer/"
  about:
    enable: true
    title: "About"
    image: "/images/me.png"
    content: "This blog is a personal journey of returning to what truly matters in life..."
    skills:
      enable: true
      title: "Here are a few things I write about:"
      items:
        - "Personal growth"
        - "Mindfulness"
        - "Intentional living"
        - "Relationships"
        - "Spirituality"
  experience:
    enable: false
    items: []
  education:
    enable: false
    items: []
  achievements:
    enable: false
    items: []
  projects:
    enable: false
    items: []
  contact:
    enable: true
    content: "My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!"
    btnName: "Mail me"
    btnLink: "mailto:sfraney@gmail.com"
  footer:
    recentPosts:
      path: "posts"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/sfraney
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
  listPages:
    disableFeaturedImage: false
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"
  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
#customScripts: -| # You can add custom scripts which will be added before </body> tag
#  <script type="text/javascript"><!-- any script here --></script>
